export const URL_TYPES = [
  'homepage',
  'pricing',
  'product',
  'features',
  'solutions',
  'about',
  'blog',
  'resources',
  'case-studies',
  'integrations',
  'customers',
  'enterprise',
  'careers',
  'docs',
  'contact',
  'support',
  'security',
  'compliance',
  'trust',
  'api',
  'changelog',
  'marketplace',
  'partners',
  'legal',
  'regulatory',
  'hipaa',
  'soc2',
  'sdk',
  'playground',
  'status',
  'sellers',
] as const;

export type UrlType = (typeof URL_TYPES)[number];

const URL_TYPE_PATHS: Record<UrlType, string> = {
  homepage: '',
  pricing: '/pricing',
  product: '/product',
  features: '/features',
  solutions: '/solutions',
  about: '/about',
  blog: '/blog',
  resources: '/resources',
  'case-studies': '/case-studies',
  integrations: '/integrations',
  customers: '/customers',
  enterprise: '/enterprise',
  careers: '/careers',
  docs: '/docs',
  contact: '/contact',
  support: '/support',
  security: '/security',
  compliance: '/compliance',
  trust: '/trust',
  api: '/api',
  changelog: '/changelog',
  marketplace: '/marketplace',
  partners: '/partners',
  legal: '/legal',
  regulatory: '/regulatory',
  hipaa: '/hipaa',
  soc2: '/soc2',
  sdk: '/sdk',
  playground: '/playground',
  status: '/status',
  sellers: '/sellers',
};

const URL_TYPE_LABELS: Record<UrlType, string> = {
  homepage: 'Homepage',
  pricing: 'Pricing',
  product: 'Product',
  features: 'Features',
  solutions: 'Solutions',
  about: 'About',
  blog: 'Blog',
  resources: 'Resources',
  'case-studies': 'Case Studies',
  integrations: 'Integrations',
  customers: 'Customers',
  enterprise: 'Enterprise',
  careers: 'Careers',
  docs: 'Documentation',
  contact: 'Contact',
  support: 'Support',
  security: 'Security',
  compliance: 'Compliance',
  trust: 'Trust Center',
  api: 'API',
  changelog: 'Changelog',
  marketplace: 'Marketplace',
  partners: 'Partners',
  legal: 'Legal',
  regulatory: 'Regulatory',
  hipaa: 'HIPAA',
  soc2: 'SOC 2',
  sdk: 'SDK',
  playground: 'Playground',
  status: 'Status',
  sellers: 'Sellers',
};

export function generatePageUrl(domain: string, type: UrlType): string {
  const path = URL_TYPE_PATHS[type] || '';
  return `https://www.${domain}${path}`;
}

export function getUrlTypeLabel(type: string): string {
  return URL_TYPE_LABELS[type as UrlType] || type.charAt(0).toUpperCase() + type.slice(1);
}
